### PR TITLE
fizzbuzz & google scraper

### PR DESCRIPTION
**Pull request by akghosh111**

### CODE REVIEW

**Comment by Tanmay-tiwari-cyber** [comment]
First follow me on GitHub
>>
>> https://www.github.com/Tanmay-Tiwaricyber

Follow this I'd by clicking on link

**Comment by Tanmay-tiwari-cyber** [comment]
First follow me on GitHub
>
> https://www.github.com/Tanmay-Tiwaricyber
Follow this I'd by clicking on link

**Comment by Tanmay-tiwari-cyber** [comment]
First follow me on GitHub
>
> https://www.github.com/Tanmay-Tiwaricyber
Follow this I'd by clicking on link

**Comment by akghosh111** [comment]
done. Please review the PR

**Comment by Tanmay-tiwari-cyber** [comment]
Done

**Pull request merged**
