### PR TITLE
Create bubble-short.py

### PR DESCRIPTION
**Pull request by adipurnamk**
added bubble short algorithm for python-program repository

### CODE REVIEW

**Comment by Tanmay-tiwari-cyber** [comment]
First follow me on GitHub
>>
>> https://www.github.com/Tanmay-Tiwaricyber

**Comment by adipurnamk** [comment]
done @Tanmay-tiwari-cyber

**Comment by Tanmay-tiwari-cyber** [comment]
First follow me on GitHub
>>
>> https://www.github.com/Tanmay-Tiwaricyber

Follow this I'd by clicking on link

**Comment by Tanmay-tiwari-cyber** [comment]
Done

**Comment by adipurnamk** [comment]
thank you @Tanmay-tiwari-cyber

**Pull request merged**
